# Site settings
title: Animesh Trivedi
email: animesh.trivedi@gmail.com
description: "Homepage of Animesh Trivedi"
baseurl: ""
url: "https://animeshtrivedi.github.io"
github_username:  animeshtrivedi

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Number of news stories on the front page.
front_page_news: 10

plugins:
  - jekyll-sitemap

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Jekyll theme inspired by researcher"

sass:
    style: compressed
    sass_dir: _sass




